# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Googlepass- Tips and Tricks How to Recover
sitename:         Googlepass
tagline:         'Tips and Tricks How to Recover'
url:              https://googlepass.net/

paginate:         2
google_analytics: 'UA-8307371-4'
bing_seo: 'FE7B6C033952978EF8BB96C0C26CA095'
email:          amit@googlepass.net

gems:             [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

github:
  repo:           https://github.com/systronics/googlepass/

tags:

twitter_username: systronics
facebook_username: systronics
linkedin_username: systronics
pinterest_username: systronics
youtube_username: amitkumarsystronics
instagram_username: systronics
telegram_username: systronics
reddit_username: googlepass
quora_username: systronics-1
github_username:  systronics
