# Dependencies
markdown:       kramdown
highlighter:    rouge

# Permalinks
permalink:      none

# Setup
name:           "Googlepass- Tips and Tricks How to Recover"
tagline:        'Googlepass'
url:            https://googlepass.net
baseurl:        ""
logo:           /public/image/logo.png
timezone:       Asia/India
 
author:
  facebook:     systronics
  twitter:      systronics
  name:         Amit Kumar
  email:        amit@googlepass.net
  
facebook:
  publisher:    systronics
  admin:        systronics
  fb:app_id:        451548405334620
  
  
facebook:
  username:     googlepass
twitter:
  username:     systronics
linkedin:
  username:     systronics
pinterest:
  username:     googlepass
youtube:
  username:     amitkumarsystronics
instagram:
  username:     systronics
telegram:
  username:     googlepass
github:
  username:     systronics

gems:           [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

google_analytics: UA-8307371-4

github:
  repo:         https://github.com/systronics/googlepass/

tags:
