# Dependencies
markdown:       kramdown
highlighter:    rouge

# Permalinks
permalink:      none

# Setup
name:           "Googlepass"
url:            https://googlepass.net
baseurl:        ""
logo:           /public/image/logo.png
timezone:       Asia/India
 
author:
  facebook:     systronics
  twitter:      systronics
  name:         Amit Kumar
  email:        admin@googlepass.net
  
facebook:
  publisher:    systronics
  admin:        systronics
  fb:app_id:        451548405334620
  
  
facebook:
  username:     systronics
twitter:
  username:     systronics
youtube:
  username:     @googlepass
instagram:
  username:     systronics
telegram:
  username:     googlepass

gems:           [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

google_analytics: UA-8307371-4

tags:
