# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Googlepass- Tips and Tricks How to Recover
tagline:         'Website is created by Amit Kumar, follow me on <a href="https://www.facebook.com/systronics" target="_blank">Facebook</a> and <a href="https://twitter.com/systronics" target="_blank">Twitter</a>'
url:              https://googlepass.net/

author:
  name:           'Amit Kumar'
  url:            https://twitter.com/systronics/

paginate:         2
google_analytics: 'UA-8307371-4'
bing_seo: 'FE7B6C033952978EF8BB96C0C26CA095'
emailme:          mailto:amit@googlepass.net

gems:             [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

github:
  repo:           https://github.com/systronics/googlepass/

tags:

twitter_username: systronics
facebook_username: systronics
linkedin_username: systronics
pinterest_username: systronics
youtube_username: amitkumarsystronics
instagram_username: systronics
telegram_username: systronics
reddit_username: googlepass
quora_username: systronics-1
github_username:  systronics
