# Dependencies
markdown:       kramdown
highlighter:    rouge

# Permalinks
permalink:      pretty

# Setup
name:           "Googlepass- Tips and Tricks How to Recover"
description:    "Googlepass offers tips and tricks how to recover Forget-password, Data-backup, Computer-repair, Website-Design, Earn-money, Equity-share, Trading-tips."
tagline:        'Tips and Tricks How to Recover'
url:            https://googlepass.net
baseurl:        ""
logo:           /public/image/logo.png
timezone:       Asia/India
email:          amit@googlepass.net

author:
  facebook:     systronics
  twitter:      systronics
  
facebook:
  app_id:       451548405334620
  publisher:    
  admin:        systronics
  
facebook:
  username:     systronics
twitter:
  username:     systronics
linkedin:
  username:     systronics
pinterest:
  username:     systronics
youtube:
  username:     amitkumarsystronics
instagram:
  username:     systronics
telegram:
  username:     amitkumarsystronics
reddit:
  username:     googlepass
quora:
  username:     systronics-1
github:
  username:     systronics
  
paginate:       1

gems:           [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

github:
  repo:         https://github.com/systronics/googlepass/

tags:
